
# spring-boot-docker/docker-compose.yml
networks:
  spring-boot-mysql-network-pedidos:
    driver: bridge
services:
  mysql-service-pedidos:
    image: mysql:5.7
    container_name: db_pedidos
    networks:
      - spring-boot-mysql-network-pedidos
    restart: always
    ports:
      - "3306:3306"
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=fiap@123
      - MYSQL_DATABASE=pedidos
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  web-service-pedidos:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-boot-mysql-network-pedidos
    depends_on:
      mysql-service-pedidos:
        condition: service_healthy